# deploy/kubernetes/overlays/prod/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: new-api-secrets
  namespace: new-api-prod # 覆盖 base 中的命名空间
type: Opaque
data:
  SESSION_SECRET: <base64_encoded_prod_SESSION_SECRET>
  CRYPTO_SECRET: <base64_encoded_prod_CRYPTO_SECRET>
  SQL_DSN: <base64_encoded_prod_SQL_DSN> # 指向生产环境 RDS
  REDIS_CONN_STRING: <base64_encoded_prod_REDIS_CONN_STRING> # 指向生产环境 Redis